sudo: false

language: node_js

node_js:
  - '6'
  - '4'
  - '0.12'
  - '0.10'

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@4.5.X
  - npm install

after_script:
  - npm run coveralls

branches:
  except:
    - /^v[0-9]/
